### ISSUE TITLE
Switch to using the i3 upstream repository

### ISSUE THREAD

**Issue by okraits** [barnumbirr/i3-gaps-debian#2]
As gaps have been basically merged in upstream i3 (https://github.com/i3/i3/pull/5241), do you plan to switch to using the i3 upstream repository for building the package?

Anyway, thank you for this project.

**Comment by barnumbirr** [comment]
Hi,

this repository will be archived when v4.22 ~~is released~~ reaches Debian Stable.

Cheers.

**Comment by okraits** [comment]
Hi,
yes, that makes sense.
Greetings.
